name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}

      - name: Build
        run: ./gradlew buildDebug

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}

      - name: Build
        run: ./gradlew testDebug

  android:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}

      - name: Build APK
        run: ./gradlew :android:assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Ivy-Wallet-APK
          path: android/build/outputs/apk/demo/*.apk

  linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle

      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}

      - name: Package Linux ".deb" distribution
        run: ./gradlew :desktop:packageReleaseDeb

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Ivy-Wallet-Linux
          path: /home/runner/work/ivy-wallet/ivy-wallet/desktop/build/compose/binaries/**/*.deb

  windows:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle

      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}

      - name: Package Windows ".msi" distribution
        run: ./gradlew :desktop:packageReleaseMsi

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Ivy-Wallet-Windows
          path: /home/runner/work/ivy-wallet/ivy-wallet/desktop/build/compose/binaries/**/*.msi

  macos:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle

      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}

      - name: Package MacOS ".dmg" distribution
        run: ./gradlew :desktop:packageReleaseDmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Ivy-Wallet-MacOS
          path: /home/runner/work/ivy-wallet/ivy-wallet/desktop/build/compose/binaries/**/*.dmg
